### PR TITLE
Add docker-compose

### PR DESCRIPTION
**Pull request by TimoKramer**

### CODE REVIEW

**Comment by TimoKramer** [comment]
the psql command does not return and I have no idea why currently. spent way too much time on this...
It's no name resolution problem so I have no clue right now.

**Comment by TimoKramer** [comment]
queue needs to be retried as well. should we do it in the entities/runners/apiservers themselves? doing some retries ? it's not so cool to have it in an entrypoint script.

**Comment by lispyclouds** [comment]
Yes, the queue needs a check too and more so because it takes a longer while than postgres to boot up. I will try to have a look and think of a good way today.

**Comment by TimoKramer** [comment]
It is possible to enable the http api and check against that. just thought it would be cool to have a retry in the application.

**Comment by lispyclouds** [comment]
Yes I think the services themselves retrying to connect would be a clean and resilient way than the external methods. For each of the services we can just try to establish a connection and retry on failure for a configurable amount of times. For our clojure services we can try to create a simple next.jdbc connection and retry till it succeeds like the example [here](https://github.com/bob-cd/bob/blob/main/runner/test/runner/util.clj#L47). Can look at the [query](https://cljdoc.org/d/seancorfield/next.jdbc/1.1.588/doc/getting-started/friendly-sql-functions#query) function in next.jdbc to do a simple `SELECT 1 + 1`. Only after this we could make the crux connection. Similarly we can do it for langhor. I would think the good place to put them would be system.clj and if these fails the app crashes and we should add a `restart: always` to the compose to tackle that.

@TimoKramer if you have the time, please go ahead with this and if you want I can take up the java one too. Otherwise I can look into both of them, soon-ish 😄

**Pull request merged**
